const_value = 0

	const MENU_TRAINER1_CLASS_POS
	const MENU_TRAINER1_ID_POS
	const MENU_TRAINER2_CLASS_POS
	const MENU_TRAINER2_ID_POS
	const MENU_LEVEL_POS
	const MENU_STATS_POS
	const MENU_ITEMS_POS
	const MENU_PPS_POS
	const MENU_MOVES_POS
	const MENU_MUSIC_POS
	const MENU_START_BATTLE_POS

MENU_MAX_INDEX EQU const_value + -1
